### ISSUE TITLE
DeepScan badge is not loading

### ISSUE THREAD

**Issue by OlegStotsky** [kalimdorjs/kalimdorjs#100]
![image](https://user-images.githubusercontent.com/9072266/47250431-278a6700-d464-11e8-8443-5623b020d733.png)

**Comment by JasonShin** [comment]
Hey @OlegStotsky  this is now resolved in https://github.com/JasonShin/kalimdorjs/tree/enhance/remove-deepscan

**Comment by JasonShin** [comment]
I also deleted the Webhook connection between github and deepscan ;)

**Comment by JasonShin** [comment]
PR for this is available at https://github.com/JasonShin/kalimdorjs/pull/102
