### ISSUE TITLE
Fix Incorrect SVM function typings

### ISSUE THREAD

**Issue by adamjking3** [kalimdorjs/kalimdorjs#145]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

The Typescript typings for the SVM.fit, SVM.predict, and SVM.predictOne functions are incorrect. This means the correct parameters cannot be passed through to libsvm-js.

* **Other information** 

Libsvm-js's `predict` method has the signature (X: Array<Array<number>>): Array<number>, however this library's SVM.predict method has the signature (X: Array<number>): Array<number>.

Libsvm-js's `predictOne` method has the signature (X: Array<number>): number, however this library's SVM.predictOne method has the signature (X: Array<number>): Array<number>.

Libsvm-js's `train` method has the signature (X: Array<Array<number>>, y: Array<number>): void, however this library's SVM.fit method has the signature (X: any[], y: any[]): void.

Similar errors can be found in the `train`, `predict`, and `predictOne` functions.

I have submitted a PR to fix these typings.

**Comment by adamjking3** [comment]
https://github.com/kalimdorjs/kalimdorjs/pull/144

**Comment by JasonShin** [comment]
Thanks ! @adamjking3 I'm closing this now
